Delete empty NBN enrollments
greenriver/hmis-warehouse pull request #1208
Opened 2020-12-03 16:50 UTC by awisema

2020-12-03 21:51 UTC, awisema commented
This will need to be integrated with the the importer extensions UI.

2020-12-03 23:24 UTC, eanders commented on drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/hmis_csv_cleanup/delete_empty_enrollments.rb
> +      enrollments_with_no_cls = enrollment_scope.where.not(id: enrollment_scope.joins(:current_living_situations).select(:id))
I think these scopes should be different.  The first just for ES TrackingMethod=3, the second only for SO.

2020-12-03 23:25 UTC, eanders commented on drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/hmis_csv_cleanup/delete_empty_enrollments.rb
> +        where(id: enrollments_with_no_cls.select(:id))
Potentially this fixes the above since it would need to be in both sets, but I bet this query will be relatively slow.

2020-12-03 23:26 UTC, eanders commented on drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/importer/project.rb
> +    end
Ah, this will only find ES TrackingMethod 3.  SO doesn't get a tracking method.

2020-12-03 23:28 UTC, eanders requested changes
See notes inline

2020-12-04 20:35 UTC, eanders commented on drivers/hmis_csv_twenty_twenty/spec/fixtures/files/delete_empty_enrollments/source/Project.csv
> +SAFE,ORG-ID,Test Project,,,,0,3,,,1,,4,3,2015-11-30 00:00:00,2015-11-30 08:50:40,user,,TEST
Need ProjectType `4` TrackingMethod `NULL`

2020-12-08 18:29 UTC, eanders commented on app/models/grda_warehouse/hud/project.rb
> +    include ::HMIS::Structure::Project
Why include it again?

2020-12-08 18:29 UTC, eanders commented on drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/hmis_csv_cleanup/delete_empty_enrollments.rb
> +        merge(HmisCsvTwentyTwenty::Importer::Project.night_by_night).
This could be `merge(HmisCsvTwentyTwenty::Importer::Project.es.night_by_night).`

2020-12-08 18:31 UTC, eanders commented on drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/hmis_csv_cleanup/delete_empty_enrollments.rb
> +      'Delete enrollments in night-by-night projects that do not have any associated services or current living situations'
This should mention SO

2020-12-08 18:33 UTC, eanders requested changes
Couple of changes, but I think it's almost there.

2020-12-08 19:28 UTC, merged