Pickers for Race, Ethnicity, Gender on population dashboards
greenriver/hmis-warehouse pull request #1360
Opened 2021-02-08 21:42 UTC by eanders

2021-02-09 19:56 UTC, awisema requested changes
Some of the supporting data is sent off to other report that don't honor the new filters.

2021-02-11 14:36 UTC, eanders commented on app/controllers/concerns/client_detail_reports.rb
> +    end
These need to be fixed!  Merge will replace previous selections

2021-02-11 14:37 UTC, eanders commented on app/controllers/warehouse_reports/first_time_homeless_controller.rb
>        scope = scope.joins(:project).merge(GrdaWarehouse::Hud::Project.viewable_by(current_user))
Does this erase the project filter?

2021-02-12 14:58 UTC, eanders commented on app/controllers/warehouse_reports/first_time_homeless_controller.rb
>        scope = scope.joins(:project).merge(GrdaWarehouse::Hud::Project.viewable_by(current_user))
Confirmed it does not.

2021-02-12 21:16 UTC, merged