Stories/visible to
greenriver/hmis-warehouse pull request #1426
Opened 2021-03-09 20:38 UTC by eanders

2021-03-23 18:57 UTC, awisema requested changes

2021-03-23 18:57 UTC, awisema commented on app/controllers/clients/history_controller.rb
> +# ###
Why not remove the file?

2021-03-23 18:57 UTC, awisema commented on app/controllers/clients/hud_lots_controller.rb
> +  # before_action :check_release, unless: :can_view_clients?
If you want to leave this in, include a comment explaining that ROIs are handled in the arbiter?

2021-03-23 18:57 UTC, awisema commented on app/controllers/clients_controller.rb
> +  before_action :require_can_view_clients_or_window!, only: [:show, :service_range, :rollup, :image, :assessment]
Can this be replaced with `require_can_view_clients` now?

2021-03-23 18:57 UTC, awisema commented on app/controllers/clients_controller.rb
> +    clean_params[:SSN] = clean_params[:SSN].gsub(/\D/, '')
`&.gsub`?

2021-03-23 18:57 UTC, awisema commented on app/controllers/clients_controller.rb
> +    # If we only have one authoritative data source, we don't bother sending it, just use it
This makes me nervous as it could result in accidentally attaching a client to the wrong authoritative data source.

2021-03-23 18:57 UTC, awisema commented on app/controllers/clients_controller.rb
>        @form = assessment_scope.find(params.require(:id).to_i)
I'm having trouble convincing myself that this is limited to the clients assessments...

2021-03-23 18:57 UTC, awisema commented on app/controllers/concerns/controller_authorization.rb
>    def require_can_see_this_client_demographics!
Could this be simplified to?
```
begin
  return true if current_user.can_view_clients?

  set_client
  return true if @client&.show_demographics_to?(current_user)
rescue ActiveRecord::RecordNotFound
  # ignore missing record
end

not_authorized!
return false
```

2021-03-23 18:57 UTC, awisema commented on app/models/concerns/user_permissions.rb
>      def can_view_clients_or_window
Remove and replace uses with `can_access_some_version_of_clients`?

2021-03-23 18:57 UTC, awisema commented on app/models/grda_warehouse/enrollment_change_history.rb
> +      attributes_for_client[:residential] = client.enrollments_for_rollup(en_scope: client.scope_for_residential_enrollments, user: User.setup_system_user).to_json rescue '[]'
These aren't limited to the current user?

2021-03-23 18:57 UTC, awisema commented on app/views/clients/_client_card.haml
> +-# - id = client.id
Delete these?

2021-03-23 18:57 UTC, awisema commented on app/views/clients/history/_history_key.haml
> +-# .history__key
Delete these?

2021-03-23 18:57 UTC, awisema commented on drivers/client_access_control/README.md
> +This README file should be used to explain the functionality of the driver.
I think a description of what this access control driver does is important.

2021-03-23 18:57 UTC, awisema commented on drivers/client_access_control/app/controllers/client_access_control/clients_controller.rb
> +  # Only allow a trusted parameter "white list" through.
'Only allow trusted parameters'

2021-03-23 18:57 UTC, awisema commented on drivers/client_access_control/app/controllers/client_access_control/search_concern.rb
> +      # Filter by population with whitelist
Filter by population with allow list

2021-03-23 18:57 UTC, awisema commented on drivers/client_access_control/extensions/grda_warehouse/service_history_enrollment_extension.rb
> +      scope :visible_to, ->(user) do
Should this return something?

2021-03-24 17:03 UTC, eanders commented on app/controllers/clients_controller.rb
> +    clean_params[:SSN] = clean_params[:SSN].gsub(/\D/, '')
SSN is null false, so it should be fine, but no harm.

2021-03-24 17:15 UTC, eanders commented on app/models/concerns/user_permissions.rb
>      def can_view_clients_or_window
replaced with can_view_clients

2021-03-24 17:16 UTC, eanders commented on app/models/grda_warehouse/enrollment_change_history.rb
> +      attributes_for_client[:residential] = client.enrollments_for_rollup(en_scope: client.scope_for_residential_enrollments, user: User.setup_system_user).to_json rescue '[]'
Right, this is a background job that stores them for future viewing, and includes all possible enrollments.

2021-04-07 18:38 UTC, merged