Stories/project group management
greenriver/hmis-warehouse pull request #1507
Opened 2021-04-19 20:40 UTC by eanders

2021-04-19 21:14 UTC, awisema requested changes
If an import file would leave a project group empty, the behavior is confusing.

2021-04-19 21:14 UTC, awisema commented on app/views/project_groups/maintenance.haml
> +- title = 'Project Group Maintenance'
Add a breadcrumb at the top to go back to the project groups page?

2021-04-19 21:14 UTC, awisema commented on app/views/project_groups/maintenance.haml
> +      %th ProjectName
Names are just for readability and not used in the import?

2021-04-19 21:14 UTC, awisema commented on app/views/project_groups/index.haml
> +      = link_to maintenance_project_groups_path, class: 'btn btn-secondary' do
`class: 'btn btn-secondary ml-2 mb-2'`

2021-04-20 12:12 UTC, eanders commented on app/models/grda_warehouse/project_group.rb
> +      return errors if parsed.empty?
@awisema this should prevent leaving an existing project group empty.

2021-04-20 13:07 UTC, eanders commented
@awisema this should be ready for a re-review, now with some simple test coverage.

2021-04-21 19:45 UTC, merged