Ensures that age range filters are symbols
greenriver/hmis-warehouse pull request #1729
Opened 2021-07-29 19:08 UTC by kwiliarty

2021-07-29 22:07 UTC, eanders requested changes
I think it's worth throwing out blanks, either by selecting present or anding it with available options.

2021-07-29 22:07 UTC, eanders commented on app/models/concerns/filter/filter_scopes.rb
> +      age_ranges = @filter.age_ranges.map(&:to_sym)
Let's throw a select present in here
```suggestion
      age_ranges = @filter.age_ranges.select(:present?).map(&:to_sym)
```

2021-07-30 13:56 UTC, kwiliarty commented on app/models/concerns/filter/filter_scopes.rb
> +      age_ranges = @filter.age_ranges.map(&:to_sym)
✅

2021-07-30 13:57 UTC, kwiliarty commented
All set.

2021-07-30 14:07 UTC, eanders approved these changes

2021-08-02 19:37 UTC, eanders commented
No longer needed, #1731 makes this obsolete.

2021-08-02 19:37 UTC, closed without merging