Rails driver for HUD CE APR
greenriver/hmis-warehouse pull request #1746
Opened 2021-08-05 18:08 UTC by eanders

2021-08-11 17:01 UTC, awisema requested changes

2021-08-11 17:01 UTC, awisema commented on drivers/hud_apr/app/models/hud_apr/generators/ce_apr/fy2020/question_four.rb
> +      # FIXME: this needs to inspect the resulting AprClients to determine which projects to include
?

2021-08-11 17:01 UTC, awisema commented on drivers/hud_apr/app/models/hud_apr/generators/ce_apr/fy2020/question_nine.rb
> +  class QuestionNine < HudApr::Generators::Shared::Fy2020::QuestionNine
This doesn't seem to really be related to `HudApr::Generators::Shared::Fy2020::QuestionNine` should it inherit from `Base` directly?

2021-08-11 17:01 UTC, awisema commented on drivers/hud_apr/app/models/hud_apr/generators/ce_apr/fy2020/question_ten.rb
> +  class QuestionTen < HudApr::Generators::Shared::Fy2020::QuestionTen
This one too -- does it use any of the shared Q10?

2021-08-11 17:01 UTC, awisema commented on drivers/hud_apr/app/controllers/hud_apr/ce_apr/apr_concern.rb
> +module HudApr::Apr::AprConcern
Is this actually used?

2021-08-11 22:45 UTC, eanders commented on drivers/hud_apr/app/models/hud_apr/generators/ce_apr/fy2020/question_four.rb
> +      # FIXME: this needs to inspect the resulting AprClients to determine which projects to include
An initial comment that turned out to be unnecessary!

2021-08-11 22:48 UTC, eanders commented on drivers/hud_apr/app/models/hud_apr/generators/ce_apr/fy2020/question_nine.rb
> +  class QuestionNine < HudApr::Generators::Shared::Fy2020::QuestionNine
I think you are correct.

2021-08-11 22:48 UTC, eanders commented on drivers/hud_apr/app/models/hud_apr/generators/ce_apr/fy2020/question_ten.rb
> +  class QuestionTen < HudApr::Generators::Shared::Fy2020::QuestionTen
I believe so

2021-08-11 22:48 UTC, eanders commented on drivers/hud_apr/app/controllers/hud_apr/ce_apr/apr_concern.rb
> +module HudApr::Apr::AprConcern
Nope, that was a bad copy paste cleanup job.

2021-08-11 22:52 UTC, eanders commented on drivers/hud_apr/app/models/hud_apr/generators/ce_apr/fy2020/question_ten.rb
> +  class QuestionTen < HudApr::Generators::Shared::Fy2020::QuestionTen
hmm, tests fail miserably if it inherits from base.  I'm going to leave it, no harm in the current inheritance.

2021-08-12 14:57 UTC, awisema approved these changes
Thanks for doing this!

2021-08-12 16:48 UTC, merged