Stories/etl for relationship to hoh
greenriver/hmis-warehouse pull request #1748
Opened 2021-08-07 13:01 UTC by eanders

2021-08-11 14:05 UTC, awisema requested changes

2021-08-11 14:05 UTC, awisema commented on drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/hmis_csv_cleanup/enforce_relationship_to_hoh.rb
> +        update_all(RelationshipToHoH: 1)
Do you need to give these clients HouseholdIDs?

2021-08-11 14:05 UTC, awisema commented on drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/hmis_csv_cleanup/enforce_relationship_to_hoh.rb
> +      enrollment_scope.where(HouseholdID: multi_person_to_fix.keys).
`# Make any HoH's 99's, leaving any other relationships -- will add HoH below`

2021-08-11 14:05 UTC, awisema commented on drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/hmis_csv_cleanup/enforce_relationship_to_hoh.rb
> +      enrollment_scope.where(HouseholdID: individual_household_ids).
`# Make sure all individuals are HoH`

2021-08-11 14:05 UTC, awisema commented on drivers/hmis_csv_twenty_twenty/app/models/hmis_csv_twenty_twenty/hmis_csv_cleanup/enforce_relationship_to_hoh.rb
> +    def cleanup!
Any touched enrollments needs the source hash updated.

2021-08-11 22:44 UTC, eanders commented
@awisema, I _think_ I got this right this time.

2021-08-12 14:44 UTC, awisema approved these changes
Looks good to me! And there are even tests!

2021-08-12 14:45 UTC, merged