Stories/performance measurement
greenriver/hmis-warehouse pull request #1876
Opened 2021-10-18 20:11 UTC by eanders

2021-11-22 16:34 UTC, awisema requested changes

2021-11-22 16:34 UTC, awisema commented on app/views/style_guides/alerts.haml
> +          .-o
`.icon-clock-o`?

2021-11-22 16:34 UTC, awisema commented on config/initializers/marginalia.rb
> +  # Marginalia::Comment.prepend_comment = true
Did you intend to turn this off in the repo?

2021-11-22 16:34 UTC, awisema commented on drivers/performance_measurement/README.md
> +This README file should be used to explain the functionality of the driver.
Yes, please :-)

2021-11-22 16:34 UTC, awisema commented on drivers/performance_measurement/app/models/performance_measurement/report.rb
> +      # binding.pry
Cleanup

2021-11-22 16:34 UTC, awisema commented on drivers/performance_measurement/app/models/performance_measurement/report.rb
> +      # TODO: remove this
?

2021-11-22 20:07 UTC, eanders commented on config/initializers/marginalia.rb
> +  # Marginalia::Comment.prepend_comment = true
Yes, I was testing what it looks like appended vs prepended.   At least in IRB/Pry it is way more readable appended.  Maybe I'll set that to `! Rails.env.development?`

2021-11-26 19:31 UTC, awisema approved these changes

2021-11-27 00:15 UTC, merged