Check for existing latest-* tag
greenriver/hmis-warehouse pull request #1908
Opened 2021-11-02 12:10 UTC by andyzito

2021-11-02 13:31 UTC, yakloinsteak requested changes
Feel like we should abort/raise exceptions if our expectations aren't met to help us with future bug-squashing. Looks good to go after that or if there's a good argument for just returning in the face of these errors.

2021-11-02 13:31 UTC, yakloinsteak commented on config/deploy/docker/lib/deployer.rb
> +      return
Should these elsif clauses raise exceptions?

2021-11-02 13:31 UTC, yakloinsteak commented on config/deploy/docker/lib/deployer.rb
> +      puts "[ERROR] No manifest matching tag #{image_tag} found during latest-* check, something is wrong."
Wonder if this should be an exception as well

2021-11-03 13:48 UTC, andyzito commented
@yakloinsteak I agree, raising an error is preferable. Code updated.

2021-11-03 14:03 UTC, merged