Stories/hic rewrite
greenriver/hmis-warehouse pull request #2036
Opened 2022-02-15 12:36 UTC by eanders

2022-02-17 16:51 UTC, awisema requested changes

2022-02-17 16:51 UTC, awisema commented on app/models/grda_warehouse/hud/funder.rb
> +      self.GrantID ||= 'Unknown'
`''` is OK here?

2022-02-17 16:51 UTC, awisema commented on app/models/grda_warehouse/hud/funder.rb
> +      end
```suggestion
      self.ProjectID =  project&.id || 'Unknown'
```

2022-02-17 16:51 UTC, awisema commented on app/models/grda_warehouse/hud/inventory.rb
> +      end
```suggestion
      self.ProjectID = project&.id || 'Unknown'
```

2022-02-17 16:51 UTC, awisema commented on app/models/grda_warehouse/hud/project.rb
> +      end
```suggestion
      # This should never happen, but does
      self.OrganizationID = organization&.id || 'Unknown'
```

2022-02-17 16:51 UTC, awisema commented on drivers/hud_hic/README.md
> +This README file should be used to explain the functionality of the driver.
```suggestion
HUD Report to generate a zip file of CSVs to unpack and upload for the HUD HIC. As of the 2022 HIC, there are no programing specs.
```

2022-02-17 16:51 UTC, awisema commented on app/views/hud_reports/_table.haml
> +  link = true unless defined?(link)
Rename to `show_link`?

2022-02-21 17:42 UTC, eanders commented on app/models/grda_warehouse/hud/funder.rb
> +      self.GrantID ||= 'Unknown'
Null False according to the Spec.

2022-03-01 23:30 UTC, merged