Follow HUDs assessment guidance more correctly
greenriver/hmis-warehouse pull request #2081
Opened 2022-03-12 15:04 UTC by eanders

2022-03-14 17:22 UTC, awisema requested changes

2022-03-14 17:22 UTC, awisema commented on app/models/concerns/hud_reports/incomes.rb
> +      #   b. and the lesser of (30 days after the [anniversary date], [report end date])
We aren't enforcing this either here or in `annual_assessment_in_window`...

2022-03-15 00:02 UTC, eanders commented on app/models/concerns/hud_reports/incomes.rb
> +      #   b. and the lesser of (30 days after the [anniversary date], [report end date])
Does https://github.com/greenriver/hmis-warehouse/pull/2081/commits/f6be32780302e8534481b0fb80c9d5388cd67d3c take care of this?

2022-03-15 13:58 UTC, awisema commented on app/models/concerns/hud_reports/incomes.rb
> +      #   b. and the lesser of (30 days after the [anniversary date], [report end date])
Looks great! Thanks!

2022-03-15 13:59 UTC, awisema approved these changes

2022-03-15 13:59 UTC, merged