Flex Services Updates
greenriver/hmis-warehouse pull request #2091
Opened 2022-03-18 18:25 UTC by awisema

2022-03-18 18:35 UTC, awisema commented
`HealthFlexibleService::Vpr.migrate_primary_languages`
To move any refused to says into the picker, and any non-picker conforming languages into the detail field.

2022-03-20 23:07 UTC, eanders commented on db/reporting_structure.sql
> +    AS $$
I'm guessing you should back out these changes as they aren't pertinent to this PR.

2022-03-20 23:10 UTC, eanders commented on drivers/health_flexible_service/app/views/health_flexible_service/warehouse_reports/member_lists/index.haml
> +        The downloaded report will include the patients with a referral to the selected ACO open
Not sure I understand the intention of this sentence.

2022-03-20 23:13 UTC, eanders commented on drivers/health_flexible_service/app/views/health_flexible_service/my_vprs/_patient_card.haml
> +- url = client_health_flexible_service_vprs_path(patient.client)
Why are these tied to client?  Shouldn't they be tied to the patient_id?

2022-03-20 23:16 UTC, eanders commented on drivers/health_flexible_service/app/views/health_flexible_service/follow_ups/show.haml
> +      %h1 #{content_for(:title)} for #{@client.full_name}
```suggestion
  - title = "Flexible Service VPR Follow Up Form for #{@client.full_name}"
  - content_for(:title, title)
  .o-page
    .o-page__header
      %h1= content_for(:title)
```

2022-03-20 23:17 UTC, eanders commented on drivers/health_flexible_service/app/views/health_flexible_service/follow_ups/new.haml
> +    %h1= "#{content_for(:title)} for #{@client.full_name}"
```suggestion
- title = "Add A Flexible Service VPR Follow Up Form for #{@client.full_name}"
- content_for(:title, title)
.o-page
  .o-page__header
    %h1= content_for(:title)
```

2022-03-20 23:17 UTC, eanders commented on drivers/health_flexible_service/app/views/health_flexible_service/follow_ups/edit.haml
> +    %h1= "#{content_for(:title)} for #{@client.full_name}"
```suggestion
- title = "Add A Flexible Service VPR Follow Up Form for #{@client.full_name}"
- content_for(:title, title)
.o-page
  .o-page__header
    %h1= content_for(:title)
```

2022-03-20 23:19 UTC, eanders commented on drivers/health_flexible_service/app/views/health_flexible_service/follow_ups/_form.haml
> +  - col_class = 'col-sm-6'
This seems excessively complicated.  I believe you could just use `row` and `col-sm-6` in both situations.

2022-03-20 23:22 UTC, eanders commented on drivers/health_flexible_service/app/controllers/health_flexible_service/follow_ups_controller.rb
> +      # TODO
What's left todo?

2022-03-20 23:23 UTC, eanders commented on drivers/health_flexible_service/app/models/health_flexible_service/member_list.rb
> +        "#{aco.short_name}_ML_R#{@r_number}_QE#{@report_range.end.strftime('%Y%m%d')}.xlsm".upcase
Should we really be up-casing the extension?

2022-03-20 23:25 UTC, eanders requested changes
See comments.

2022-03-24 15:33 UTC, awisema commented on drivers/health_flexible_service/app/views/health_flexible_service/my_vprs/_patient_card.haml
> +- url = client_health_flexible_service_vprs_path(patient.client)
This would require a significant restructuring. The VPRs/FollowUps are tied to the patient, but the controllers use the client id and then find the patient through the client. Deferring this for now.

2022-03-24 16:36 UTC, eanders requested changes
Looks great!

2022-03-24 16:41 UTC, eanders approved these changes

2022-03-24 16:42 UTC, merged