Add Favorite reports feature
greenriver/hmis-warehouse pull request #2118
Opened 2022-04-01 19:38 UTC by gigxz

<img width="1272" alt="Screen Shot 2022-04-01 at 2 31 13 PM" src="https://user-images.githubusercontent.com/5333982/161329973-6620322b-56fe-4048-b697-13c60ea324ca.png">
<img width="284" alt="Screen Shot 2022-04-01 at 2 30 59 PM" src="https://user-images.githubusercontent.com/5333982/161330071-8d1e2641-2ee9-4543-9a59-ab8788dde419.png">
<img width="1290" alt="Screen Shot 2022-04-01 at 3 35 33 PM" src="https://user-images.githubusercontent.com/5333982/161330131-9f58fd4e-12cc-44a7-95f4-2e439342a64a.png">

---
screenshots showing click targets:
<img width="965" alt="Screen Shot 2022-04-01 at 12 50 13 PM" src="https://user-images.githubusercontent.com/5333982/161330038-bc49391f-d490-4e35-b581-65027eb1e385.png">
<img width="979" alt="Screen Shot 2022-04-01 at 12 50 09 PM" src="https://user-images.githubusercontent.com/5333982/161330040-c5568cb2-5d92-4165-90e7-bd37c393cdd0.png">

2022-04-01 20:47 UTC, eanders requested changes

2022-04-01 20:47 UTC, eanders commented on app/controllers/api/reports_controller.rb
> +    end
This would be cleaner to specify two routes, `favorite` as a put and `unfavorite` as a delete, or just one route, that includes a param of `favorite` true or false.  It doesn't feel right (or follow patterns I'm aware of within the app) to check the method of the request to make the determination.

2022-04-01 20:47 UTC, eanders commented on app/assets/javascripts/warehouse_reports/favorite.js.es6
> +      async: false,
you can remove this line

2022-04-01 20:47 UTC, eanders commented on config/routes.rb
> +      delete :favorite, on: :member
let's `put :unfavorite`

2022-04-01 20:47 UTC, eanders commented on app/controllers/api/reports_controller.rb
> +        current_user.favorite_reports << report
```suggestion
       Favorite.create(entity_id: params[:id].to_i, current_user: current_user.id, entity_type: 'GrdaWarehouse::WarehouseReports::ReportDefinition)
```

2022-04-01 20:47 UTC, eanders commented on app/controllers/api/reports_controller.rb
> +        current_user.favorite_reports.delete(report)
```suggestion
        current_user.favorite_reports.where(entity_id: params[:id].to_i).destroy_all
```

2022-04-04 15:13 UTC, gigxz commented on sample.env
> +CAS_DATABASE_DB_TEST=test_openpath_cas
Unrelated missing environment variable that caused `db:reset` to fail because the database didn't have a name.

2022-04-04 15:35 UTC, eanders approved these changes
@gigxz, this looks great and does exactly what it says on the tin.  Thanks!

2022-04-04 18:21 UTC, merged