Ea/data lab
greenriver/hmis-warehouse pull request #2393
Opened 2022-08-19 16:23 UTC by eanders

2022-10-06 19:06 UTC, eanders commented
@awisema, if you can review this, that'd be great.  There's one failing test that passes locally.  Need to see if I can run the entire test suite locally and duplicate the issue to fix before we merge.

2022-10-11 18:19 UTC, awisema requested changes
Some small clean up suggestions; it is such a relief to see this over the finishline!

2022-10-11 18:19 UTC, awisema commented on app/models/grda_warehouse/hud/enrollment.rb
> +      at_entry.joins(:enrollment).where(ib_t[:InformationDate].eq(e_t[:EntryDate]))
You rolled the date match into `at_entry`/`at_exit` , so these are redundant?

2022-10-11 18:19 UTC, awisema commented on app/models/grda_warehouse/hud/income_benefit.rb
> +      where(DataCollectionStage: 1).joins(:enrollment).where(ib_t[:InformationDate].eq(e_t[:EntryDate]))
Are these ever used for DQ? In which case, do you need to add something like `-> (on_date: true)`?

2022-10-11 18:19 UTC, awisema commented on drivers/hmis_csv_twenty_twenty_two/spec/models/exporter/multi_enrollment_tests.rb
>            end.map { |m| [m.id, m.EnrollmentID, m.data_source_id] }
Dead code?

2022-10-11 18:19 UTC, awisema commented on drivers/hud_apr/app/models/hud_apr/generators/shared/fy2021/base.rb
> +          # Only include income at start if the information date matches entry date
Done in `income_benefits_at_entry`?

2022-10-11 18:19 UTC, awisema commented on drivers/hud_spm_report/app/models/hud_spm_report/generators/fy2020/base.rb
> +          # data labe test kit seems to reject any homeless time
I think the AAQ confirmed this behavior as correct? Update this to reflect the referenced explanation?

2022-10-11 18:19 UTC, awisema commented on drivers/hud_spm_report/app/models/hud_spm_report/generators/fy2020/base.rb
> +          # binding.pry if debug
```suggestion
```

2022-10-11 18:19 UTC, awisema commented on spec/rails_helper.rb
> +      # FileUtils.rm(filename)
```suggestion
      # This cleans up the fixpoints before each rspec run
      # Disabling the next line, can make iterative test development faster.
      FileUtils.rm(filename)
```

2022-10-12 16:12 UTC, awisema approved these changes

2022-10-12 16:14 UTC, merged