HMIS viewable entities
greenriver/hmis-warehouse pull request #2570
Opened 2022-11-01 19:30 UTC by eanders

2022-11-01 20:23 UTC, awisema requested changes

2022-11-01 20:23 UTC, awisema commented on app/models/concerns/hmis_enabled.rb
> +    end
Could `application_helper.rb` and `enforce_hmis_enabled.rb` use this instead of having 3 copies?

2022-11-01 20:23 UTC, awisema commented on app/models/concerns/hmis_enabled.rb
> +    end
And maybe pull `hmis_admin_visible?` into here as well?

2022-11-01 20:23 UTC, awisema commented on drivers/hmis/app/models/hmis/hud/assessment.rb
> +    enrollment_ids = Hmis::Hmis::Enrollment.viewable_by(user).pluck(:id, :EnrollmentID)
I think these changes (here, enrollment, funder, inventory, and project coc), are accidental?

2022-11-01 20:23 UTC, awisema commented on app/views/admin/roles/_new_form.haml
> -  .form-actions
Maybe pass `value` into `new_form` so, you can leave this in here?

2022-11-01 20:23 UTC, awisema commented on drivers/hmis/app/models/hmis/hud/organization.rb
> +    viewable_ids += user.organizations..pluck(:id)
```suggestion
    viewable_ids += user.organizations.pluck(:id)
```

2022-11-01 22:33 UTC, eanders commented on drivers/hmis/app/models/hmis/hud/assessment.rb
> +    enrollment_ids = Hmis::Hmis::Enrollment.viewable_by(user).pluck(:id, :EnrollmentID)
Oh, yeah, messed those up.

2022-11-02 20:58 UTC, gigxz commented
Looks good! I tested it out and confirmed that only assigned projects are viewable in the HMIS 🥳 
I don't see a way to assign HMIS Roles to users/groups. Is that missing, or am I not seeing it?

2022-11-02 22:16 UTC, eanders commented
Yeah, the assignment of users to roles and groups is slightly awkward at the moment, but it's there!

2022-11-03 13:26 UTC, gigxz approved these changes
Looks good to me!

Just to confirm what I'm seeing: all _clients_ in the user's HMIS Data source are visible to the user. What this looks like in the HMIS, if you're only assigned to a couple projects: you can still search across clients, but most of the clients will appear as if they have no enrollments. I think that's all correct.

2022-11-03 14:26 UTC, eanders commented
That's the current setup, we may want to apply a `visible_to` to Client, but we haven't yet.

2022-11-03 18:17 UTC, merged