Logging task runs
greenriver/hmis-warehouse pull request #2624
Opened 2022-11-18 21:02 UTC by eanders

2022-11-18 21:37 UTC, yakloinsteak approved these changes

2022-11-18 21:51 UTC, eanders commented on app/models/grda_warehouse/tasks/push_clients_to_cas.rb
>          logger.warn msg
Need to check the remaining file too
```suggestion
        Rails.logger.warn msg
```

2022-11-18 21:51 UTC, eanders commented on app/models/grda_warehouse/tasks/project_cleanup.rb
> +    attr_accessor :send_notifications, :notifier_config
No longer need these
```suggestion

```

2022-11-30 20:18 UTC, awisema requested changes
A few minor tweaks, and a question...

2022-11-30 20:18 UTC, awisema commented on app/models/bo/client_id_lookup.rb
>        Rails.logger.info msg
You rolled this into `ping`, so these are all duplicates, yes?

2022-11-30 20:18 UTC, awisema commented on app/models/bo/client_id_lookup.rb
>        Rails.logger.info msg
I think the separate `msg` assignment is also unnecessary, and hurts readability, at least for me...

2022-11-30 20:18 UTC, awisema commented on app/models/bo/client_id_lookup.rb
> +            if msg.present?
`msg` is set above, so this is redundant.

2022-11-30 20:18 UTC, awisema commented on app/models/concerns/export/exporter.rb
> +      Rails.logger.info message if @debug
Can we make sure `@notifier` is always set, and remove the logger line? I think this will produce double messages if `@debug` is set

2022-11-30 20:18 UTC, awisema commented on app/models/grda_warehouse/tasks/sanity_check_service_history.rb
> +    attr_accessor :send_notifications
I don't think this ever gets set? And then it guards a ping down on line 64... Not sure what the correct behavior is, do we want that check?

2022-12-01 14:06 UTC, eanders commented on app/models/grda_warehouse/tasks/sanity_check_service_history.rb
> +    attr_accessor :send_notifications
I believe it gets set in NotifierConfig (which is included) but I believe we can tear it out since ping now has the guard.

2022-12-01 14:11 UTC, eanders commented on app/models/concerns/export/exporter.rb
> +      Rails.logger.info message if @debug
Yep, @notifier should always be set now, and ping always sends to logger.info, so this can get cleaned up.  Thanks.

2022-12-01 14:15 UTC, eanders commented on app/models/bo/client_id_lookup.rb
> +            if msg.present?
yes!, and there are bunch of 
```
Rails.logger.info msg
@notifier.ping msg
```
which are also redundant!

2022-12-01 14:17 UTC, merged