Zeitwerk
greenriver/hmis-warehouse pull request #2769
Opened 2023-01-19 20:19 UTC by eanders

2023-01-20 19:15 UTC, awisema requested changes
4 comments for 452 files, looks good to me! Just a couple of changes.

2023-01-20 19:15 UTC, awisema commented on drivers/boston_project_scorecard/app/views/boston_project_scorecard/warehouse_reports/scorecards/_project_quality.haml
> +          CoC and HUD threshold for funding and is not eligible for inclusion in the Boston CoC 2022 application to HudUtility.
```suggestion
          CoC and HUD threshold for funding and is not eligible for inclusion in the Boston CoC 2022 application to HUD.
```

2023-01-20 19:15 UTC, awisema commented on drivers/project_scorecard/app/views/project_scorecard/warehouse_reports/scorecards/_data_quality.haml
> +%p= simple_format(_('HMIS participation and data quality are priorities for TX-601 & HudUtility. Accurate, complete & timely data is crucial to determine how projects are contributing to ending homel
```suggestion
%p= simple_format(_('HMIS participation and data quality are priorities for TX-601 & HUD. Accurate, complete & timely data is crucial to determine how projects are contributing to ending homelessness.  High quality data is key to understanding what projects are doing and how the CoC & HUD can make informed decisions about the project.'))
```

2023-01-20 19:15 UTC, awisema commented on locale/en/hmis_warehouse.edit.po
> +msgid "HMIS participation and data quality are priorities for TX-601 & HudUtility. Accurate, complete & timely data is crucial to determine how projects are contributing to ending homelessness.  High
Rather than edit this here, I think we should regen the translation strings?

2023-01-20 19:15 UTC, awisema commented on lib/tasks/us_census_api.rake
> +    GrdaWarehouse::UsCensusApi::CocAgg.run!
I don't think `GrdaWarehouse::UsCensusApi::CoCAgg` got renamed?

2023-01-23 14:35 UTC, yakloinsteak approved these changes
Github says 448 files changed, but I only see a diff of 7, so I'll just comment here:

Is the structure.sql diff just catching things up? I wouldn't expect anything new there. That's the only thing that I noticed. Looks good.

2023-01-23 19:11 UTC, merged