Add ExitProcessor to AssessmentProcessor.
greenriver/hmis-warehouse pull request #2799
Opened 2023-02-06 14:47 UTC by awisema

2023-02-06 15:16 UTC, gigxz approved these changes
Looks good, thanks! I will incorporate into the `assessment_date` logic in my branch

2023-02-06 16:42 UTC, gigxz commented on drivers/hmis/spec/models/hmis/form/assessment_processor_spec.rb
> +    it 'adds an exit record when appropriate' do
Looks like this is failing:

```
  1) Hmis::Form::AssessmentProcessor updating existing assessment adds an exit record when appropriate
     Failure/Error: @processor.send(factory_name, create: false)&.assign_attributes(information_date: date)

     ActiveModel::UnknownAttributeError:
       unknown attribute 'information_date' for Hmis::Hud::Exit.
```

2023-02-07 13:14 UTC, gigxz requested changes
Just needs a fix on failing tests

2023-02-07 18:41 UTC, awisema commented
Not sure why I thought these were passing... Fixed.

2023-02-07 18:45 UTC, gigxz approved these changes

2023-02-07 18:46 UTC, merged