Me/184076457 service history calendar
greenriver/hmis-warehouse pull request #3303
Opened 2023-07-25 15:16 UTC by meborn

2023-07-25 18:59 UTC, eanders commented on drivers/client_access_control/app/controllers/client_access_control/history_controller.rb
> +      @month_index = params[:month_index].present? ? (params[:month_index].to_i || 0) : nil
I _think_ this is equivalent to:
```suggestion
      @month_index = params[:month_index].to_i
```
since `nil.to_i` returns zero.

2023-08-14 19:27 UTC, awisema requested changes

2023-08-14 19:27 UTC, awisema commented on app/assets/javascripts/d3_charts/clientHistoryCalendar.js.es6
> +    this.container = d3.select('.d3-calendar')
```suggestion
    this.container = d3.select(calendar_selector)
```

2023-08-14 19:27 UTC, awisema commented on app/assets/javascripts/d3_charts/clientHistoryCalendar.js.es6
> +  constructor(data, eventsData, calendar_selector) {
`eventsData` doesn't seem to be used?

2023-08-14 19:27 UTC, awisema commented on app/assets/javascripts/d3_charts/clientHistoryCalendar.js.es6
> +    var parts = dateString.split('-')
Philosophical question: if you are in ES6, is when is `var` preferable to `let`/`const`? (Question applies to all the `var`s below).

2023-08-14 19:27 UTC, awisema commented on app/assets/javascripts/d3_charts/clientHistoryCalendar.js.es6
> +        var opacity = 1
Dead code?

2023-08-14 19:27 UTC, awisema commented on app/assets/javascripts/d3_charts/clientHistoryCalendar.js.es6
> +          })
Maybe really a GitHub complaint -- but I found matching these close params up to the functions that they go with difficult...

2023-08-14 19:27 UTC, awisema commented on app/assets/javascripts/d3_charts/clientHistoryCalendar.js.es6
> +      tooltipTriggers.each(function(d, index) {
Similar question -- when do you use `function(...) {` and when do you use `(...) => {`

2023-08-14 19:27 UTC, awisema commented on drivers/client_access_control/app/models/client_access_control/client_history_month.rb
> +class ClientAccessControl::ClientHistoryMonth
Missing copyright notice, and don't we usually separate out the the module name?

2023-08-14 23:52 UTC, merged