Patch CDE bug
greenriver/hmis-warehouse pull request #3329
Opened 2023-07-31 14:59 UTC by gigxz

I misunderstood how the `scope` param works, and I still don't really get what it's supposed to do https://www.rubydoc.info/docs/rails/ActiveRecord/Associations/Preloader#initialize-instance_method. But it doesn't filter down the results, which is what we need.

2023-07-31 15:03 UTC, gigxz commented
oops, not  ready for review

2023-07-31 16:00 UTC, ttoomey requested changes
Thanks for fixing this! A small change needed I think, happy to discuss if you have any questions

2023-07-31 16:00 UTC, ttoomey commented on drivers/hmis/app/graphql/types/hmis_schema/custom_data_element.rb
> +      load_ar_association(object, :values).where(id: ids)
So `load_ar_association` returns an AR scope that is preloaded. However if you call `where` or `pluck` on it (or some other method that maps to a DB operation), then the preloaded value is ignored and a new DB query is made. This is true for any preloaded scope in rails, not just the graphql preloader.

So I'd suggest either not preloading here (since we would discard the value anyway) or using array operations instead:
```suggestion
      ids = load_ar_association(parent, :custom_data_elements).map(&:id).to_set
      # get all values existing for this CustomDataElementDefinition, and filter
      # it down to only elemnts that are relevant to this parent
      load_ar_association(object, :values).filter { |v| v.id.in?(ids) }
```

2023-07-31 16:00 UTC, ttoomey commented on drivers/hmis/app/graphql/types/hmis_schema/custom_data_element.rb
> -      load_ar_association(object, :values, scope: parent.custom_data_elements)
Sorry I didn't catch this earlier. The third scope argument is hard to understand, I was confused about this too. We Probably should add some documentation to the preloader to clarify how it's used.

My understanding is the scope is intended for ordering or to modify the default association in a way that is constant with respect to the resolver, for example `scope = FooBar.order(:name)`

2023-07-31 16:28 UTC, gigxz commented on drivers/hmis/app/graphql/types/hmis_schema/custom_data_element.rb
> +      load_ar_association(object, :values).where(id: ids)
Ahh okay, I see. Super helpful explanation. I'll switch to array operations.

2023-07-31 16:29 UTC, gigxz commented on drivers/hmis/app/graphql/types/hmis_schema/custom_data_element.rb
> -      load_ar_association(object, :values, scope: parent.custom_data_elements)
Oh okay, that makes sense. I'll put a comment in there!

2023-08-01 14:33 UTC, ttoomey approved these changes
Looks great, thank you!

2023-08-01 15:56 UTC, merged