FY 2024 hud utility usage updates
greenriver/hmis-warehouse pull request #3434
Opened 2023-08-28 19:19 UTC by eanders

2023-09-06 13:05 UTC, gigxz commented on lib/util/hud_utility_2024.rb
> +      99 => :RaceNone,
Whoops, thanks!

2023-09-06 13:30 UTC, gigxz commented on app/models/concerns/performance_dashboard/overview/detail.rb
> +    when 'Woman', 'Man', 'NonBinary', 'CulturallySpecific', 'DifferentIdentity', 'Transgender', 'Questioning', 'Unknown Gender'
If these are headers, shouldn't they be "Non-Binary", "Culturally Specific" "Different Identity" ?

2023-09-06 13:31 UTC, gigxz approved these changes

2023-09-07 13:51 UTC, eanders commented on app/models/concerns/performance_dashboard/overview/detail.rb
> +    when 'Woman', 'Man', 'NonBinary', 'CulturallySpecific', 'DifferentIdentity', 'Transgender', 'Questioning', 'Unknown Gender'
Yes, probably but deferring that work since I don't want to break the related code yet.

2023-09-12 15:47 UTC, awisema requested changes

2023-09-12 15:47 UTC, awisema commented on app/models/grda_warehouse/hud/client.rb
>        gender_transgender.where(Male: 1)
Should this be
```suggestion
      gender_transgender.where(Man: 1)
```
?

2023-09-12 19:41 UTC, merged