LSA FY 2024
greenriver/hmis-warehouse pull request #3650
Opened 2023-10-17 19:59 UTC by eanders

## Description

LSA for FY2024

## Type of change
- [ ] Bug fix
- [ ] New feature (adds functionality)
- [ ] Code clean-up / housekeeping
- [ ] Dependency update

## Checklist before requesting review
- [ ] I have performed a self-review of my code
- [ ] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [ ] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [ ] My code follows the style guidelines of this project (rubocop)
- [ ] I have updated the documentation (or not applicable)
- [ ] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

2023-10-19 16:14 UTC, awisema requested changes
I'm loving these well architected parts of the system! One thing to check, and some ideas for more DRY code...

2023-10-19 16:14 UTC, awisema commented on drivers/hud_lsa/app/models/hud_lsa/generators/fy2023/lsa.rb
> +            version: 2023,
Should this be 2024?

2023-10-19 16:14 UTC, awisema commented on drivers/hud_lsa/app/models/hud_lsa/generators/fy2023/lsa.rb
> +        version: '2023',
2024?

2023-10-19 16:14 UTC, awisema commented on drivers/hud_lsa/app/models/hud_lsa/generators/fy2023/lsa.rb
> +        remove_primary_key = false
Maybe move to `else` branch below - I'm not sure, but in cases like this, it feels less like a default, and more like an explicit choice?

2023-10-19 16:14 UTC, awisema commented on drivers/hud_lsa/app/models/hud_lsa/generators/fy2023/lsa.rb
> +          headers = klass.csv_columns.map { |m| if m == :Zip then :ZIP else m end }.map(&:to_s)
How does this relate to `standardize_headers` above?

2023-10-19 16:14 UTC, awisema commented on drivers/hud_lsa/app/models/hud_lsa/generators/fy2023/lsa.rb
> +    def fetch_intermediate_results
Can this be DRY'd up w/ above?

2023-10-19 16:14 UTC, awisema commented on drivers/hud_lsa/app/models/hud_lsa/generators/fy2023/table_concern.rb
> +      if not exists (select * from sys.indexes where name = 'IX_sys_Time_sysStatus')
Seems like this might be more maintainable made into a hash?

```
{
  IX_sys_Time_sysStatus: '[sys_Time] ([sysStatus])',
  …
}.each do |index, on|
 create_index(index, on) if !exists…
```

2023-10-20 17:18 UTC, eanders commented on drivers/hud_lsa/app/models/hud_lsa/generators/fy2023/lsa.rb
> +          headers = klass.csv_columns.map { |m| if m == :Zip then :ZIP else m end }.map(&:to_s)
Pretty sure it's undoing the above.  Basically, we chose to store the column as `Zip` but the spec is `ZIP`

2023-10-20 17:26 UTC, eanders commented on drivers/hud_lsa/app/models/hud_lsa/generators/fy2023/table_concern.rb
> +      if not exists (select * from sys.indexes where name = 'IX_sys_Time_sysStatus')
maybe, though in this case I think I'd prefer the straight up SQL for now.  Only had to change a few small items this year, hopefully that's similar next year.

2023-10-26 19:25 UTC, merged