APR/CAPER 2024 v1.2 updates
greenriver/hmis-warehouse pull request #3718
Opened 2023-11-10 16:18 UTC by eanders

## Description

This updates the APR and CAPER to the newest version of the spec and updates the definition of "parenting youth" to match the response from the Data Lab.

## Type of change
- [ ] Bug fix
- [ ] New feature (adds functionality)
- [ ] Code clean-up / housekeeping
- [ ] Dependency update

## Checklist before requesting review
- [ ] I have performed a self-review of my code
- [ ] I have run the code that is being changed under ideal conditions, and it doesn't fail
- [ ] My code includes comments and/or descriptive variable names to help other engineers understand the intent (or not applicable)
- [ ] My code follows the style guidelines of this project (rubocop)
- [ ] I have updated the documentation (or not applicable)
- [ ] If it's not obvious how to test this change, I have provided testing instructions in this PR or the related issue

2023-11-10 18:01 UTC, awisema requested changes

2023-11-10 18:01 UTC, awisema commented on app/models/concerns/hud_reports/households.rb
> +      age = universe_client
I think something got lost here
```suggestion
      age = universe_client.age
```
?

2023-11-10 18:14 UTC, eanders commented on app/models/concerns/hud_reports/households.rb
> +      age = universe_client
Whops!

2023-11-13 22:09 UTC, awisema approved these changes

2023-11-13 22:09 UTC, awisema commented on app/models/grda_warehouse/ch_enrollment.rb
> +        is_no?(value)
Maybe
```suggestion
       :no
```
To be consistent?

2023-11-13 22:09 UTC, awisema commented on app/models/grda_warehouse/ch_enrollment.rb
> +        is_no?(value)
```suggestion
        :no
```

2023-11-14 00:42 UTC, merged